### ISSUE TITLE
.sdfcli.json error message when accidentally clicking empty entry box for environment

### ISSUE THREAD

**Issue by christopherwxyz** [mark-keaton/NetSuiteSDF#1]
Steps to reproduce: 

1. Click SDF bottom left hand corner

2. Click the empty entry box.

3. Error message pops up, the SDF environment is reverts to plain SDF.

<img width="997" alt="screen shot 2018-02-21 at 4 13 57 pm" src="https://user-images.githubusercontent.com/362387/36488017-a643d9dc-1722-11e8-8d60-72256b85af9d.png">

**Comment by mark-keaton** [comment]
Confirmed and reproduced.
