### ISSUE TITLE
Need an icon for Marketplace

### ISSUE THREAD

**Issue by mark-keaton** [mark-keaton/NetSuiteSDF#16]

**Comment by christopherwxyz** [comment]
don't think this can be anything NS related (in fact, are we in a grey area by even using NetSuite in the title of this repo?). 

i vote voodoo doll, but that's just me

**Comment by JonnyBoy333** [comment]
Some ideas to get the ball rolling. Mostly stuff I found online and some light photoshoping. I think if we don't use the NetSuite logo and disclaim that we are not affiliated with NetSuite Corp we'll be ok. That's what the Slack group did at least.

![logo-edited2](https://user-images.githubusercontent.com/15164008/48389694-4b884380-e6c4-11e8-9821-3430ed0ad5ff.png)
![logo-edited](https://user-images.githubusercontent.com/15164008/48389714-635fc780-e6c4-11e8-9dac-41943ad1b5ee.png)

**Comment by mark-keaton** [comment]
@JonnyBoy333 Nice work!

Let me see what I can do with that.

**Comment by mark-keaton** [comment]
![image](https://user-images.githubusercontent.com/3433130/48416620-52d83d00-e716-11e8-9f8a-8ee098c7ac0f.png)

Looks good to me @JonnyBoy333!

@christopherwxyz thoughts?

Closing.
