### ISSUE TITLE
No way to know if SDF is actually installed

### ISSUE THREAD

**Issue by christopherwxyz** [mark-keaton/NetSuiteSDF#2]
It's possible to run the plugin and navigate the menu system without actually having sdfcli installed. Running any command produces a silent fail.

**Comment by mark-keaton** [comment]
Don't really like this solution. I think I'd really prefer to go to decorators instead of this verbose method, but I couldn't get the decorators to do what I want.
I'll have to look into decorators again later.

I will push a release to the VS Code marketplace with this fix soon.
