### ISSUE TITLE
Windows bug -- sdfcli path is broken

### ISSUE THREAD

**Issue by christopherwxyz** [mark-keaton/NetSuiteSDF#3]
Trying to run the CLI in windows results in a broken path.

C:/c:/User/path/sdfcli instead of C:/User/path/sdfcli

**Comment by mark-keaton** [comment]
@christopherwxyz can you give me some more details?

Where does this happen? At what point do you see this? When does it break?

I'll probably have to install SDFCLI on my Windows machine to test this.

**Comment by konofo** [comment]
I encountered what I assume is the same problem.  To reproduce, load a folder with an .sdf file, but no .sdfcli.json.  In this scenario, clicking SDF in the status bar gets you into getConfig, which should end up creating the .sdfcli.json file.

I found that getConfig was setting rootPath to ...uri.path, which in my case was "/c:/dev/SDF/HelloWorld".  The leading slash leads to the error mentioned above:

```
ENOENT: no such file or directory, open 'C:\c:\dev\SDF\HelloWorld\.sdfcli.json'
```

Luckily, the uri object also has an fsPath, which seems to be preferable, at least on Windows:
```
fsPath:"c:\dev\SDF\HelloWorld"
path:"/c:/dev/SDF/HelloWorld"
```

Switching to fsPath got me past the error.  I don't know if it is the answer for everyone.

**Comment by mark-keaton** [comment]
Good catch. Now that I have Windows users, I'll have to try and fix this.

Thanks for the input!

**Comment by ViktorSch** [comment]
Hi @mark-keaton ,

Sorry for being dumb but could you advise me the exact file where I need to switch to fsPath please? Tried to search for uri.path and getConfig but there are too many and a nice pile of work is waiting for me anyway...

Thanks in advance.
Viktor

**Comment by ViktorSch** [comment]
It's here:
c:\Users\"user"\.vscode\extensions\markkeaton.netsuitesdf-0.3.1\out\netsuite-sdf.js

**Comment by mark-keaton** [comment]
Anyone confirm this is still happening? If no response, I'll close in a few days.
